export const NAVITEMS_REQUESTING = "NAVITEMS_REQUESTING";
export const NAVITEMS_WORKFLOW_ADD = "NAVITEMS_WORKFLOW_ADD";
export const NAVITEMS_SUCCESS = "NAVITEMS_SUCCESS";
export const NAVITEMS_FAILURE = "NAVITEMS_FAILURE";

export const OPENTEABS_LIST = "OPENTABS_LIST";
